FROM python:3.9

WORKDIR /project

COPY . bk-fornax/.
WORKDIR /project/bk-fornax

RUN ["pip", "install", "-e", ".[interactive,tuto]"]
WORKDIR /project/bk-fornax/docs/tutorial


# Add Tini. Tini operates as a process subreaper for jupyter. This prevents kernel crashes.
ENV TINI_VERSION v0.6.0
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /usr/bin/tini
RUN chmod +x /usr/bin/tini
ENTRYPOINT ["/usr/bin/tini", "--"]

CMD ["jupyter", "notebook", "--port=8888", "--no-browser", "--ip=0.0.0.0", "--allow-root"]